version: '3.8'
services:
  postgres:
    build:
      dockerfile: Dockerfile.db
    container_name: app
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
  app:
    build:
      dockerfile: Dockerfile.app
    ports:
      - 8080:8080
    depends_on:
      - postgres