version: '3.3'
services:
  mypostgres:
    image: "postgres"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
  app:
    build: .
    container_name: app
    ports:
      - 8080:8080
    depends_on:
      - mypostgres