version: '1.0'
services:
  postgres:
    build:
      dockerfile: Dockerfile.db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - "db-data:/var/lib/postgresql/data"
  app:
    build:
      dockerfile: Dockerfile.app
    image: 'app'
    ports:
      - 8080:8080
    depends_on:
      - postgres

volumes:
  db-data: